- package.json
- samples/package.json
Release notes forthcoming in the next comment.
> Bump version to v0.4.0

- .circleci/config.yml
Fixes one outdated reference to `system_tests` in `.circleci/config.yml`.
> Remove reference to system tests.

- .cloud-repo-tools.json
- README.md
- package.json
- protos/google/cloud/videointelligence/v1/video_intelligence.proto
- samples/README.md
- samples/analyze.js
- samples/package.json
- src/index.js
- src/v1/doc/google/cloud/videointelligence/v1/doc_video_intelligence.js
- src/v1/doc/google/protobuf/doc_any.js
- src/v1/doc/google/protobuf/doc_duration.js
- src/v1/doc/google/rpc/doc_status.js
- src/v1/index.js
- src/v1/video_intelligence_service_client.js
- src/v1/video_intelligence_service_client_config.json
- test/gapic-v1.js
This PR adds the `v1` endpoint to video intelligence _and_ marks the library as GA.
This PR should *not* be merged until just before the November 15 rollout.
> Add the v1 (stable) endpoint.

- samples/analyze.js
Typo in the command argument name
(I'm not sure if I need to do something to regen the README?)
> Change <gcsUri> to <filePath> for labels-file command

- package.json
- samples/analyze.js
- samples/package.json
- samples/system-test/analyze.test.js
> Added Video Transcription sample code.

- protos/google/cloud/videointelligence/v1p1beta1/video_intelligence.proto
- src/index.js
- src/v1p1beta1/doc/google/cloud/videointelligence/v1p1beta1/doc_video_intelligence.js
> updated GAPIC code for v1p1beta1

- package-lock.json
- package.json
- samples/package-lock.json
- samples/package.json
Revision version of video intelligence
> bump version to 1.2.0

- samples/analyze.js
- samples/system-test/analyze.test.js
Removed the face detection sample code per Cameron's request.
> Removed the face detection sample code and the unit test

- samples/analyze.js
- src/index.js
Updates region tags to be consistent with those in other languages. Region tag update on cloud.google.com is also in progress and will be submitted after all language PRs are merged.
> Video Intelligence region tag update

- CHANGELOG.md
- package.json
- samples/package.json
This pull request was generated using releasetool.
> Release @google-cloud/video-intelligence v1.4.0

- CHANGELOG.md
- package.json
- samples/package.json
This pull request was generated using releasetool.
> Release @google-cloud/video-intelligence v1.4.1

- .eslintignore
- samples/analyze.js
- samples/analyze.v1p2beta1.js
- samples/quickstart.js
Fixes googleapis/google-cloud-node#2869 (it's a good idea to open an issue first for discussion)
Fixes https://github.com/googleapis/nodejs-video-intelligence
> docs(samples): updated samples code to use async await

- samples/analyze.js
> refactor(samples): drop beta usage from the samples

- CHANGELOG.md
- package.json
- samples/package.json
This pull request was generated using releasetool.
> Release @google-cloud/video-intelligence v1.5.1

- .kokoro/test.bat
- src/v1/video_intelligence_service_client.js
- src/v1/video_intelligence_service_client_config.json
- src/v1beta1/video_intelligence_service_client_config.json
- src/v1beta2/video_intelligence_service_client_config.json
- src/v1p1beta1/video_intelligence_service_client_config.json
- src/v1p2beta1/video_intelligence_service_client_config.json
- src/v1p3beta1/streaming_video_intelligence_service_client_config.json
- src/v1p3beta1/video_intelligence_service_client_config.json
- synth.metadata
- system-test/video_intelligence_service_smoke_test.js
- test/gapic-v1.js
temporary patch broken Windows container, such that tests can be run on Node 10
> fix: DEADLINE_EXCEEDED no longer treated as idempotent and retried 

- samples/analyze.js
- samples/analyze.v1p2beta1.js
> fix: correct typo in example command

- samples/analyze.js
- samples/analyze.v1p2beta1.js
> fix: Update example commands to use cloud-storage-samples bucket

- samples/system-test/analyze_face_detection.test.js
- samples/system-test/analyze_face_detection_gcs.test.js
- samples/system-test/analyze_person_detection.test.js
- samples/system-test/analyze_person_detection_gcs.test.js
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
> docs: relax the tests for face / person detection

- samples/detect_logo.js
- samples/detect_logo_gcs.js
- samples/system-test/detect_logo.test.js
- samples/system-test/detect_logo_gcs.test.js
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
> docs: move samples out of branch and add tests

- .gitignore
- samples/detect_logo.js
- samples/detect_logo_gcs.js
This pull request adds the following samples:
- video_detect_logo_gcs
- video_detect_logo
These samples are GA versions of existing beta samples; once the GA versions are submitted and the documentation updated, the beta versions will be deleted (in a separate PR).
> feat: logo recognition updates
